const  words = [
    "MRR", 
    "Revenue", 
    "Sales", 
    "Pizza",
    "This quarter", 
    "2024", 
    "Funding", 
    "Awesome work", 
    "Thank you", 
    "Growth", 
    "Projections", 
    "Numbers",
    "Financials", 
    "Graph", 
    "Market", 
    "Marketing", 
    "This week", 
    "Strong", 
    "Stringent", 
    "Economy", 
    "Users", 
    "Research", 
    "Feedback", 
    "Product", 
    "Product-market-fit", 
    "Phonecall", 
    "Escalation", 
    "Support", 
    "Work-from-home", 
    "Remote", 
    "Office"
]

export default words